[theme]
primaryColor="#ffd000ff"  #cor de destaque (bordas, sider) do app
backgroundColor="#000000ff"  # cor do fundo das pagina
secondaryBackgroundColor="#78139aff" # cor secundária dos fundos das páginas (menu, tabelas, etc)
textColor="#ffffffff" # cor do texto do app
font="serif" # a fonte do app