[theme]
primaryColor="#ffd000ff"  #cor de destaque (bordas, sider) do app
backgroundColor="rgb(255, 255, 255)"  # cor do fundo das pagina
secondaryBackgroundColor="#78139aff" # cor secundária dos fundos das páginas (menu, tabelas, etc)
textColor="rgb(0, 0, 0)" # cor do texto do app
font="serif" # a fonte do app